### PR TITLE
monitoring: Add cluster and pool utilization collectd plugins

### PR DESCRIPTION
**Pull request by anmolbabu**
This patch adds collectd plugin to collect cluster utilization
and pool utilization. The stats are then written to time series
db by the plugin configured as write plugin. And hence this patch
is only specific to collectd and has nothing to do with time series
db.

Signed-off-by: anmolbabu anmolbudugutta@gmail.com

### CODE REVIEW

**Comment by anmolbabu** [comment]
@nthomas-redhat @shtripat can you please review this patch

**Review by shtripat — APPROVED** [review]

**Review by r0h4n — CHANGES_REQUESTED** [review]
please format your commit msg as per #66

And mention spec name

**Comment by r0h4n** [comment]
This needs spec name and/or github issue in commit msg

**Comment by r0h4n** [comment]
@anmolbabu I am going to close this if not required, please respond

**Comment by r0h4n** [comment]
Is this still relevant?

**Comment by anmolbabu** [comment]
It is relevant but we can revive it back when we do sds-specific monitoring

**Pull request closed without merging**
