### PR TITLE
Request_is is replace by job_id in job_update message

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/specifications#28
tendrl-spec: logging_implementation

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @anivargi @brainfunked  please review

**Review by shtripat — COMMENTED** [review]
LGTM. Mark it verified.

**Comment by r0h4n** [comment]
Please send this on develop branch

**Comment by GowthamShanmugam** [comment]
@Tendrl/tendrl-core shubhendu's namespace PR(https://github.com/Tendrl/ceph-integration/pull/151) alreading have this changes, so i am going to close this

**Pull request closed without merging**
