### PR TITLE
Renamed tendrl-cephd.service to tendrl-ceph-integration.service 

### PR DESCRIPTION
**Pull request by anmolsachan**
Renamed tendrl-cephd.service to tendrl-ceph-integration.service and replaced its usage.

tendrl-bug-id: Tendrl/ceph-integration#77
Signed-off-by: anmolsachan asachan@redhat.com

### CODE REVIEW

**Review by shtripat — COMMENTED** [review]
LGTM

**Comment by r0h4n** [comment]
Is this still required?

**Comment by mbukatov** [comment]
Why was this closed?

**Comment by mbukatov** [comment]
Ah, it was actually fixed by different commit: 7e00f620a01cd218e6d874e3528e653d453a5d5f

**Pull request closed without merging**
