### PR TITLE
fix for cluster_tendrl_context details are not populated correctly

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/ceph-integration#176

Signd-off-by: root <root@dhcp42-67.lab.eng.blr.redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nnDarshan please review

**Comment by GowthamShanmugam** [comment]
As per discussion with @nnDarshan and  @shtripat  i have sent a fix patch for cluster_tendrl_context in ceph-integration

**Review by nnDarshan — COMMENTED** [review]
LGTM.
@GowthamShanmugam Please verify if this solves the problem

**Comment by r0h4n** [comment]
This has been fixed: https://github.com/Tendrl/node-agent/issues/328

Please verify

**Pull request closed without merging**
