### PR TITLE
Namespaces changes

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
Yet to be verified

**Comment by shtripat** [comment]
Verified the changes with cluster details sync, crud flows for pool, rbd amd ec-profiles.
Works fine now.

**Comment by r0h4n** [comment]
Please send this on develop branch

**Comment by shtripat** [comment]
Closing this and would send to `develop` branch.

**Pull request closed without merging**
